apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: ovro-npm-test
  namespace: ovro-system
spec:
  workspaces:
    - name: source
  steps:
    - name: test
      image: node:20
      workingDir: $(workspaces.source.path)/console-plugin
      env:
        - name: npm_config_cache
          value: $(workspaces.source.path)/.cache/npm
      script: |
        #!/bin/sh
        set -ex
        mkdir -p $npm_config_cache
        npm test
