FROM golang:1.26.2 AS builder
WORKDIR /workspace
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -o approval-proxy cmd/approval-proxy/main.go

FROM registry.access.redhat.com/ubi9/ubi-minimal:9.6
WORKDIR /
COPY --from=builder /workspace/approval-proxy .
USER 65532:65532
ENTRYPOINT ["/approval-proxy"]
