apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: victoriametrics-network-policy
  namespace: ovro-system
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: victoriametrics
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ovro-system
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: openshift-monitoring
      ports:
        - port: 8428
          protocol: TCP
