//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlgorithmSpec) DeepCopyInto(out *AlgorithmSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlgorithmSpec.
func (in *AlgorithmSpec) DeepCopy() *AlgorithmSpec {
	if in == nil {
		return nil
	}
	out := new(AlgorithmSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoModeSpec) DeepCopyInto(out *AutoModeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoModeSpec.
func (in *AutoModeSpec) DeepCopy() *AutoModeSpec {
	if in == nil {
		return nil
	}
	out := new(AutoModeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPUSpec) DeepCopyInto(out *CPUSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPUSpec.
func (in *CPUSpec) DeepCopy() *CPUSpec {
	if in == nil {
		return nil
	}
	out := new(CPUSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsSnapshot) DeepCopyInto(out *MetricsSnapshot) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsSnapshot.
func (in *MetricsSnapshot) DeepCopy() *MetricsSnapshot {
	if in == nil {
		return nil
	}
	out := new(MetricsSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectRef) DeepCopyInto(out *ObjectRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectRef.
func (in *ObjectRef) DeepCopy() *ObjectRef {
	if in == nil {
		return nil
	}
	out := new(ObjectRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceSpec) DeepCopyInto(out *ResourceSpec) {
	*out = *in
	out.CPU = in.CPU
	out.Memory = in.Memory.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceSpec.
func (in *ResourceSpec) DeepCopy() *ResourceSpec {
	if in == nil {
		return nil
	}
	out := new(ResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RightsizingPolicy) DeepCopyInto(out *RightsizingPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RightsizingPolicy.
func (in *RightsizingPolicy) DeepCopy() *RightsizingPolicy {
	if in == nil {
		return nil
	}
	out := new(RightsizingPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RightsizingPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RightsizingPolicyList) DeepCopyInto(out *RightsizingPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RightsizingPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RightsizingPolicyList.
func (in *RightsizingPolicyList) DeepCopy() *RightsizingPolicyList {
	if in == nil {
		return nil
	}
	out := new(RightsizingPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RightsizingPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RightsizingPolicySpec) DeepCopyInto(out *RightsizingPolicySpec) {
	*out = *in
	out.Algorithm = in.Algorithm
	in.Thresholds.DeepCopyInto(&out.Thresholds)
	out.AutoMode = in.AutoMode
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RightsizingPolicySpec.
func (in *RightsizingPolicySpec) DeepCopy() *RightsizingPolicySpec {
	if in == nil {
		return nil
	}
	out := new(RightsizingPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RightsizingRecommendation) DeepCopyInto(out *RightsizingRecommendation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RightsizingRecommendation.
func (in *RightsizingRecommendation) DeepCopy() *RightsizingRecommendation {
	if in == nil {
		return nil
	}
	out := new(RightsizingRecommendation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RightsizingRecommendation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RightsizingRecommendationList) DeepCopyInto(out *RightsizingRecommendationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RightsizingRecommendation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RightsizingRecommendationList.
func (in *RightsizingRecommendationList) DeepCopy() *RightsizingRecommendationList {
	if in == nil {
		return nil
	}
	out := new(RightsizingRecommendationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RightsizingRecommendationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RightsizingRecommendationSpec) DeepCopyInto(out *RightsizingRecommendationSpec) {
	*out = *in
	out.VirtualMachineRef = in.VirtualMachineRef
	in.Current.DeepCopyInto(&out.Current)
	in.Recommended.DeepCopyInto(&out.Recommended)
	in.Savings.DeepCopyInto(&out.Savings)
	out.Metrics = in.Metrics
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RightsizingRecommendationSpec.
func (in *RightsizingRecommendationSpec) DeepCopy() *RightsizingRecommendationSpec {
	if in == nil {
		return nil
	}
	out := new(RightsizingRecommendationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RightsizingRecommendationStatus) DeepCopyInto(out *RightsizingRecommendationStatus) {
	*out = *in
	if in.LastCalculated != nil {
		in, out := &in.LastCalculated, &out.LastCalculated
		*out = (*in).DeepCopy()
	}
	if in.AppliedAt != nil {
		in, out := &in.AppliedAt, &out.AppliedAt
		*out = (*in).DeepCopy()
	}
	if in.ScheduledRestartAt != nil {
		in, out := &in.ScheduledRestartAt, &out.ScheduledRestartAt
		*out = (*in).DeepCopy()
	}
	if in.RevertBefore != nil {
		in, out := &in.RevertBefore, &out.RevertBefore
		*out = (*in).DeepCopy()
	}
	if in.RevertConfig != nil {
		in, out := &in.RevertConfig, &out.RevertConfig
		*out = new(ResourceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.NotifiedAt != nil {
		in, out := &in.NotifiedAt, &out.NotifiedAt
		*out = (*in).DeepCopy()
	}
	if in.ApprovedAt != nil {
		in, out := &in.ApprovedAt, &out.ApprovedAt
		*out = (*in).DeepCopy()
	}
	if in.RejectedAt != nil {
		in, out := &in.RejectedAt, &out.RejectedAt
		*out = (*in).DeepCopy()
	}
	if in.ReminderSentAt != nil {
		in, out := &in.ReminderSentAt, &out.ReminderSentAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RightsizingRecommendationStatus.
func (in *RightsizingRecommendationStatus) DeepCopy() *RightsizingRecommendationStatus {
	if in == nil {
		return nil
	}
	out := new(RightsizingRecommendationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SavingsSpec) DeepCopyInto(out *SavingsSpec) {
	*out = *in
	out.Memory = in.Memory.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SavingsSpec.
func (in *SavingsSpec) DeepCopy() *SavingsSpec {
	if in == nil {
		return nil
	}
	out := new(SavingsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThresholdsSpec) DeepCopyInto(out *ThresholdsSpec) {
	*out = *in
	out.MinMemorySavings = in.MinMemorySavings.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThresholdsSpec.
func (in *ThresholdsSpec) DeepCopy() *ThresholdsSpec {
	if in == nil {
		return nil
	}
	out := new(ThresholdsSpec)
	in.DeepCopyInto(out)
	return out
}
