name: Tests

on:
  push:
  pull_request:

jobs:
  unit-tests:
    name: Go unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run Go tests
        run: |
          go mod tidy
          make test

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Run console plugin tests
        working-directory: console-plugin
        run: |
          npm ci
          npm test
